# Generated by Django 5.1.4 on 2025-01-18 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumemaster',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='resumemaster',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='resumesectionmapping',
            name='creation_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='resumesectionmapping',
            name='modified_time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='sectionmaster',
            name='section_creation_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='sectionmaster',
            name='section_modified_time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='subsectionmaster',
            name='creation_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='subsectionmaster',
            name='modified_time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
