# Generated by Django 5.1.4 on 2025-01-18 14:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templts', '0002_alter_resumemaster_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldMaster',
            fields=[
                ('field_id', models.AutoField(primary_key=True, serialize=False)),
                ('field_name', models.CharField(max_length=100)),
                ('field_type', models.CharField(max_length=100)),
                ('field_creation_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('field_modified_time', models.DateTimeField(auto_now=True, null=True)),
                ('active_status', models.BooleanField(default=True)),
                ('field_order', models.IntegerField(default=1)),
                ('field_created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_fields', to=settings.AUTH_USER_MODEL)),
                ('field_modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_fields', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'field_master',
                'ordering': ['field_order', 'field_name'],
            },
        ),
        migrations.AddField(
            model_name='resumesectionmapping',
            name='field_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='templts.fieldmaster'),
            preserve_default=False,
        ),
    ]
