# Generated by Django 5.1.4 on 2025-01-18 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('templts', '0003_fieldmaster_resumesectionmapping_field_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fieldmaster',
            options={'ordering': ['field_name']},
        ),
        migrations.RemoveField(
            model_name='fieldmaster',
            name='field_order',
        ),
    ]
