# Generated by Django 5.1.4 on 2025-01-18 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templts', '0004_alter_fieldmaster_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumesectionmapping',
            name='field_order',
            field=models.IntegerField(default=0),
        ),
    ]
