# Generated by Django 5.1.4 on 2025-02-01 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templts', '0005_resumesectionmapping_field_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumemaster',
            name='ats',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='resumemaster',
            name='downloads',
            field=models.DecimalField(decimal_places=3, default=3.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='resumemaster',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=4.0, max_digits=5),
        ),
    ]
